"""Add edges handles

Revision ID: 24a5993a37ac
Revises: a83bf9ab81dc
Create Date: 2025-04-30 14:14:58.734987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a5993a37ac'
down_revision = 'a83bf9ab81dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_handle', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_handle', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_column('target_handle')
        batch_op.drop_column('source_handle')

    # ### end Alembic commands ###
