"""ORM based Added config filed to project and damagescenario model

Revision ID: 763a8892cac7
Revises: 811f06f2a380
Create Date: 2025-05-12 19:42:27.565866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763a8892cac7'
down_revision = '811f06f2a380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('security_property', sa.String(length=20), nullable=False),
    sa.Column('controlability', sa.String(length=10), nullable=False),
    sa.Column('corporate_flag', sa.String(length=50), nullable=False),
    sa.Column('road_users', sa.Text(), nullable=False),
    sa.Column('business', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_damage_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('damage_scenario_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['damage_scenario_id'], ['damage_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'damage_scenario_id', name='uix_config_damage')
    )
    op.create_table('project_damage_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('damage_scenario_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['damage_scenario_id'], ['damage_scenarios.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'damage_scenario_id', name='uix_project_damage')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_damage_scenarios')
    op.drop_table('configuration_damage_scenarios')
    op.drop_table('damage_scenarios')
    # ### end Alembic commands ###
