"""Added config filed to project and damagescenario model

Revision ID: 811f06f2a380
Revises: 78b100f74813
Create Date: 2025-05-12 18:25:00.140861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811f06f2a380'
down_revision = '78b100f74813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'configurations', ['config_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('config_id')

    # ### end Alembic commands ###
